dj_cookbook/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from dj_cookbook import views

app_name='cookbook'
urlpatterns = [
    path('', views.index, name='index'),
    #ingredients
    path('ingredients/create/', login_required(views.IngredientCreate.as_view()), name='ingredient-create'),
    path('ingredients/all/', views.IngredientList.as_view(), name='ingredient-list'),
    path('ingredients/<pk>/', views.IngredientDetail.as_view(), name='ingredient-detail'),
    path('ingredients/<pk>/update', login_required(views.IngredientUpdate.as_view()), name='ingredient-update'),
    path('ingredients/<pk>/delete', login_required(views.IngredientDelete.as_view()), name='ingredient-delete'),
    #meals
    path('meals/create/', login_required(views.MealCreate.as_view()), name='meal-create'),
    path('meals/all/', views.MealList.as_view(), name='meal-list'),
    path('meals/add-recipe/', login_required(views.meal_add_recipe), name='meal-add-recipe'),
    path('meals/<pk>/', views.MealDetail.as_view(), name='meal-detail'),
    path('meals/<pk>/update', login_required(views.MealUpdate.as_view()), name='meal-update'),
    path('meals/<pk>/delete', login_required(views.MealDelete.as_view()), name='meal-delete'),
    #recipes
    path('recipes/create/', login_required(views.RecipeCreate.as_view()), name='recipe-create'),
    path('recipes/all/', views.RecipeList.as_view()),
    path('recipes/<pk>/', views.RecipeDetail.as_view(), name='recipe-detail'),
    path('recipes/<pk>/update', login_required(views.RecipeUpdate.as_view()), name='recipe-update'),
    path('recipes/<pk>/delete', login_required(views.RecipeDelete.as_view()), name='recipe-delete'),
]

dj_cookbook/models.py
from django.db import models
from django.urls import reverse

class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    unit = models.CharField(max_length=100,
                            choices=(('ct', 'Count'),
                                     ('cup', '1 Cup'),
                                     ('tbsp', 'TBSP'),
                                     ('tsp', 'TSP')),
                            default='cup')
    type = models.CharField(max_length=25,
                            choices=(('poultry', 'Poultry'),
                                     ('fish', 'Fish'),
                                     ('meat', 'Meat'),
                                     ('fruit', 'Fruit'),
                                     ('vegetable', 'Vegetable'),
                                     ('starch', 'Starch'),
                                     ('other', 'Other'))
                            )
    calories = models.FloatField()
    fat = models.FloatField()
    satfat = models.FloatField()
    cholesterol = models.FloatField()
    sodium = models.FloatField()
    carbs = models.FloatField()
    fiber = models.FloatField()
    sugar = models.FloatField()
    protein = models.FloatField()
    
    def get_absolute_url(self):
        return reverse('cookbook:ingredient-detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return(self.name)

class Meal(models.Model):
    name = models.CharField(max_length=100)
    winter = models.BooleanField(default=True)
    spring = models.BooleanField(default=True)
    summer = models.BooleanField(default=True)
    fall = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('cookbook:meal-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return(self.name)
    
class Recipe(models.Model):
    meal = models.ForeignKey('Meal', on_delete=models.CASCADE)
    ingredient = models.ForeignKey('Ingredient', on_delete=models.CASCADE)
    amount = models.FloatField(default=1)

    def get_absolute_url(self):
        return reverse('cookbook:recipe-detail', kwargs={'pk': self.pk})

    
    def __str__(self):
        return('{} - {} - {}'.format(self.meal, self.ingredient, self.amount))
    

dj_cookbook/forms.py
from django import forms
from .models import *

   
class MealRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['ingredient', 'amount']

        

dj_cookbook/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse

from dj_cookbook.models import *
import dj_cookbook.forms as forms
import pdb

def index(request):
    return render(request, 'dj_cookbook/index.html')

    
class IngredientCreate(CreateView):
    model = Ingredient
    fields = "__all__"

class IngredientDetail(DetailView):
    model = Ingredient

class IngredientList(ListView):
    model = Ingredient
    
class IngredientUpdate(UpdateView):
    model = Ingredient
    fields = "__all__"

class IngredientDelete(DeleteView):
    model = Ingredient
    success_url="/cookbook/"

class MealCreate(CreateView):
    model = Meal
    fields = "__all__"

class MealDetail(DetailView):
    model = Meal
    def get_context_data(self, **kwargs):
        context = super(MealDetail, self).get_context_data(**kwargs)
        context['mealRecipeForm'] = forms.MealRecipeForm()
        return context
    
@login_required    
def meal_add_recipe(request):
    meal = Meal.objects.get(pk=request.POST.get('meal'))
    ingredient = Ingredient.objects.get(pk=request.POST.get('ingredient'))
    amount = request.POST.get('amount')

    Recipe.objects.get_or_create(
        meal=meal,
        ingredient=ingredient,
        amount=amount)

    return(HttpResponse(True))
    
class MealList(ListView):
    model = Meal
    
class MealUpdate(UpdateView):
    model = Meal
    fields = "__all__"

class MealDelete(DeleteView):
    model = Meal
    success_url="/cookbook/"

class RecipeCreate(CreateView):
    model = Recipe
    fields = "__all__"

class RecipeDetail(DetailView):
    model = Recipe

class RecipeList(ListView):
    model = Recipe

class RecipeUpdate(UpdateView):
    model = Recipe
    fields = "__all__"

class RecipeDelete(DeleteView):
    model = Recipe
    success_url="/cookbook/"

    

dj_cookbook/templates/dj_cookbook/footer.html
<footer class="footer bg-dark">
  <div class="container">
    <span class="text-muted">Site built by Ben Miller <a href="mailto:bsmiller25@gmail.com"><span class="octicon octicon-mail"</span></a> <a href="https://github.com/bsmiller25"><span class="octicon octicon-mark-github"></span></a> <a href="https://www.linkedin.com/in/bsmiller25/"><span class="fab fa-linkedin"></span></a></span>
  </div>
</footer> 

dj_cookbook/templates/dj_cookbook/index.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <br>
    <div class="row justify-content-center">
      <div class="col-8">
	<h1>Welcome to the Cookbook!</h1>
      </div>
    </div>
  </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/ingredient_confirm_delete.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<form method="post">{% csrf_token %} 
	  <p>Are you sure you want to delete "{{ object }}"?</p> 
	  <input type="submit" value="Confirm">
	</form>
      </div>
    </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/ingredient_detail.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<h1>{{ object.name }}</h1>

	<h4>{{ object.get_type_display }}</h4>

	<h4>Nutrition</h4>
	Per {{ object.unit }}
	<table class="table">
	  <tbody>
	    <tr>
	      <td>Calories</td>
	      <td>{{ object.calories }}</td>
	    </tr>
	    <tr>
	      <td>Fat</td>
	      <td>{{ object.fat }} g</td>
	    </tr>
	    <tr>
	      <td>Saturated Fat</td>
	      <td>{{ object.satfat }} g</td>
	    </tr>
	    <tr>
	      <td>Cholesterol</td>
	      <td>{{ object.cholesterol }} mg</td>
	    </tr>
	    <tr>
	      <td>Sodium</td>
	      <td>{{ object.sodium }} mg</td>
	    </tr>
	    <tr>
	      <td>Carbs</td>
	      <td>{{ object.carbs }} g</td>
	    </tr>
	    <tr>
	      <td>Fiber</td>
	      <td>{{ object.fiber }} g</td>
	    </tr>
	    <tr>
	      <td>Sugar</td>
	      <td>{{ object.sugar }} g</td>
	    </tr>
	    <tr>
	      <td>Protein</td>
	      <td>{{ object.protein }} g</td>
	    </tr>
	  </tbody>     
	  
	</table>

	<h3>Meals</h3>
	{% for recipe in object.recipe_set.all %}
	  <li><a href="{% url 'cookbook:meal-detail' pk=recipe.meal.id %}">{{ recipe.meal }}</a></li>
	{% endfor %}
	  

      </div>
    </div>
  </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/ingredient_form.html
{% extends 'dj_cookbook/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <hr class="mt-0 mb-4">
	<form method="POST" enctype="multipart/form-data">  
	  {% csrf_token %} 
	  
	  {{ form|crispy}} 
	  
	  <input type="submit" value="Submit" class="btn btn-success">
	</form>
      </div>
    </div>
  </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/ingredient_list.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<h1>All Ingredients</h1>
	<a href="{% url 'cookbook:ingredient-create' %}" class="btn btn-primary">New Ingredient</a>
	<table class="table">
	  <thead>
	    <th>Name</th>
	    <th>Unit</th>
	    <th>Type</th>
	    <th>Actions</th>
	  </thead>
	  <tbody>
	    {% for object in object_list %}
	      <tr>
		<td>{{ object.name }}</td>
		<td>{{ object.get_unit_display }}</td>
		<td>{{ object.get_type_display }}</td>
		<td><a href="{% url 'cookbook:ingredient-detail' pk=object.id %}"><i class="fa fa-info fa-2x"></i></a>     <a href="{% url 'cookbook:ingredient-delete' pk=object.id %}"> <i class="fa fa-trash fa-2x"></i></a> </td>
	      </tr>
	    {% empty %} 
	      <li>No ingredients yet.</li> 
	    {% endfor %}
	  </tbody>
	</table>
      </div>
    </div>
  </div>
{% endblock %}
 

dj_cookbook/templates/dj_cookbook/meal_confirm_delete.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<form method="post">{% csrf_token %} 
	  <p>Are you sure you want to delete "{{ object }}"?</p> 
	  <input type="submit" value="Confirm">
	</form>
      </div>
    </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/meal_detail.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<h1>{{ object.name }}</h1>
	<h3>Seasons</h3>
	{% if object.winter %}Winter {% endif %}{% if object.spring %}Spring {% endif %}{% if object.summer %}Summer {% endif %}{% if object.fall %}Fall{% endif %}
	<h3>Ingredients</h3>

	<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add Ingredient</button>

	<!-- Modal -->
	<div class="modal fade" id="myModal" role="dialog">
	  <div class="modal-dialog">
	    
	    <!-- Modal content-->
	    <div class="modal-content">
              <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="modal-title">Add Ingredient</h4>
              </div>
              <div class="modal-body">
		{% csrf_token %} 
		{{ mealRecipeForm.as_p }}
              </div>
              <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<button type="button" id="saveRecipe" class="btn btn-success">Save</button>
              </div>
	    </div> 
	  </div>
	</div>
	<table class="table">
	  <thead>
	    <th>Ingredient</th>
	    <th>Amount</th>
	    <th>Actions</th>
	  </thead>
	  <tbody>
	    {% for recipe in object.recipe_set.all %}
	      <tr>
		<td><a href={% url 'cookbook:ingredient-detail' pk=recipe.ingredient.id %}>{{ recipe.ingredient }}</a></td>
		<td>{{ recipe.amount }} {{ recipe.ingredient.unit }}</td>
		<td><a href="{% url 'cookbook:recipe-update' pk=recipe.id %}">Edit</a> <a href="{% url 'cookbook:recipe-delete' pk=recipe.id %}">Delete</a></td>
	      </tr>
	    {% endfor %}
	  </tbody>
	</table>
      </div>
    </div>
  </div>

  <script>
   $('#saveRecipe').click(function(){
       newRecipe();
   });

   function newRecipe(){
       $("#myModal").modal('hide')

       $.post("/cookbook/meals/add-recipe/",
	      {csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
	       meal: {{ object.id }},
	       ingredient: $("select[name=ingredient]").val(),
	       amount: $("input[name=amount]").val()
	      })
	.done(function(msg){
	    location.reload()
	})
   };
   
  </script>
{% endblock %}

dj_cookbook/templates/dj_cookbook/meal_form.html
{% extends 'dj_cookbook/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <hr class="mt-0 mb-4">
	<form method="POST" enctype="multipart/form-data">  
	  {% csrf_token %} 
	  
	  {{ form|crispy}} 
	  
	  <input type="submit" value="Submit" class="btn btn-success">
	</form>
      </div>
    </div>
  </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/meal_list.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<h1>All Meals</h1>
	<a href="{% url 'cookbook:meal-create' %}" class="btn btn-primary">New Meal</a>
	<ul> 
	  {% for object in object_list %} 
	    <li><a href="{% url 'cookbook:meal-detail' pk=object.id %}">{{object.name }}</a></li> 
	  {% empty %} 
	    <li>No meals yet.</li> 
	  {% endfor %} 
	</ul> 
      </div>
    </div>
  </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'cookbook:index' %}">Our Cookbook!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
	<a class="nav-link" href="{% url 'cookbook:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nat-item">
	<a class="nav-link" href={% url 'cookbook:meal-list' %}>Meals</a>
      </li>
      <li class="nav-item">
	<a class="nav-link" href={% url 'cookbook:ingredient-list' %}>Ingredients</a>
      </li>
    </ul>
  </div>
</nav> 

dj_cookbook/templates/dj_cookbook/recipe_confirm_delete.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<form method="post">{% csrf_token %} 
	  <p>Are you sure you want to delete "{{ object }}"?</p> 
	  <input type="submit" value="Confirm">
	</form>
      </div>
    </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/recipe_detail.html
{% extends 'dj_cookbook/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<h1>{{ object.meal }} {{ object.ingredient }} {{ object.amount }} {{ object.ingredient.unit }}</h1>
      </div>
    </div>
  </div>
{% endblock %}

dj_cookbook/templates/dj_cookbook/recipe_form.html
{% extends 'dj_cookbook/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <hr class="mt-0 mb-4">
	<form method="POST" enctype="multipart/form-data">  
	  {% csrf_token %} 
	  
	  {{ form|crispy}} 
	  
	  <input type="submit" value="Submit" class="btn btn-success">
	</form>
      </div>
    </div>
  </div>
{% endblock %}